### ISSUE TITLE
java.nio.BufferOverflowException in HeapByteBuffer.java:233

### ISSUE THREAD

**Issue by DMDirc-git** [DMDirc/dmdirc3#237]
## Error in DMDirc3

**java.nio.BufferOverflowException** in **HeapByteBuffer.java:233**

[View on Bugsnag](https://app.bugsnag.com/dmdirc/dmdirc3/errors/5c8a68a3567fa10018d717b6?event_id=5c8a68a3003777a3cd310000&i=gh&m=ci)

## Stacktrace

    HeapByteBuffer.java:233 - java.nio.HeapByteBuffer.put

[View full stacktrace](https://app.bugsnag.com/dmdirc/dmdirc3/errors/5c8a68a3567fa10018d717b6?event_id=5c8a68a3003777a3cd310000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by csmith** [comment]
https://github.com/csmith/KtIrc/issues/16
