### ISSUE TITLE
org.kodein.di.Kodein$DependencyLoopException in App.kt:135

### ISSUE THREAD

**Issue by DMDirc-git** [DMDirc/dmdirc3#243]
## Error in DMDirc3

**org.kodein.di.Kodein$DependencyLoopException** in **App.kt:135**
Dependency recursion:
     bind<MainContract.Controller>()
    ╔╩>bind<ConnectionContract.Controller>()
    ║  ╚>bind<NotificationManager>()
    ║    ╚>bind<MainContract.Controller>()
    ╚══════╝

[View on Bugsnag](https://app.bugsnag.com/dmdirc/dmdirc3/errors/5c8ab21b2c68400019df30e5?event_id=5c8ab21b00377b835f2a0000&i=gh&m=ci)

## Stacktrace

    App.kt:135 - com.dmdirc.AppKt$createKodein$1$14.invoke
    App.kt:-1 - com.dmdirc.AppKt$createKodein$1$14.invoke
    App.kt:141 - com.dmdirc.AppKt$createKodein$1$15.invoke
    App.kt:-1 - com.dmdirc.AppKt$createKodein$1$15.invoke
    MainController.kt:44 - com.dmdirc.MainController.connect
    ServerlistDialog.kt:77 - com.dmdirc.ServerListController.connect
    ServerlistDialog.kt:156 - com.dmdirc.ServerListModel.connectPressed
    ServerlistDialog.kt:280 - com.dmdirc.ServerlistDialog$$special$$inlined$apply$lambda$24.handle
    ServerlistDialog.kt:191 - com.dmdirc.ServerlistDialog$$special$$inlined$apply$lambda$24.handle

[View full stacktrace](https://app.bugsnag.com/dmdirc/dmdirc3/errors/5c8ab21b2c68400019df30e5?event_id=5c8ab21b00377b835f2a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by csmith** [comment]
Dev error
